algorithm: fullysupervised
save_dir: ./saved_models/usb_cv/
save_name: fullysupervised_food101_202_0
resume: True
load_path: ./saved_models/usb_cv//fullysupervised_food101_202_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 200
num_train_iter: 204800
num_log_iter: 256
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 10240
num_labels: 202
uratio: 1
ema_m: 0.0
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.75
momentum: 0.9
weight_decay: 0.03
amp: True
clip: 0.0
use_cat: True
net: vit_base_patch16_224
net_from_name: False
data_dir: ./data
dataset: food101
train_sampler: RandomSampler
num_classes: 101
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10001
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/mae_pretrain_vit_base.pth
