algorithm: textmatch
save_dir: ./saved_models/usb_cv/
save_name: textmatch_eurosat_40_3_2
resume: True
load_path: ./saved_models/usb_cv//textmatch_eurosat_40_3_2/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_train_iter: 102400
num_log_iter: 256
num_eval_iter: 1024
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 20480
num_labels: 40
uratio: 1
ema_m: 0.0
hard_label: True
T: 0.5
ema_p: 0.999
ent_loss_ratio: 0
img_size: 32
crop_ratio: 0.875
optim: AdamW
lr: 1e-05
layer_decay: 1.0
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: vit_small_patch2_32
net_from_name: False
data_dir: ./data
dataset: eurosat
train_sampler: RandomSampler
num_classes: 10
num_workers: 4
seed: 3
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10082
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_small_patch2_32_mlp_im_1k_32.pth
text_model: clip
long_text: False
lambda_c: 0.1
lambda_ortho: 0.1
contras_tempeture: 0.05
vt_proj: multi_head_attn_text