algorithm: msnfreematch
save_dir: ./saved_models/msn_usb_cv/
save_name: msnfreematch_cifar100_200_0
resume: True
load_path: ./saved_models/msn_usb_cv//msnfreematch_cifar100_200_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 200
num_train_iter: 204800
num_log_iter: 256
num_eval_iter: 1024
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 5120
num_labels: 200
uratio: 4
ema_m: 0.998
hard_label: True
T: 0.5
ent_loss_ratio: 0.001
img_size: 32
crop_ratio: 0.875
optim: AdamW
lr: 0.001
layer_decay: 0
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: False
net: msn_vit_small_patch2_32
net_from_name: False
use_strongaug_mae: True
mix_noise: True
lambda_mixed_loss: 0.5
data_dir: ./data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 8
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10211
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_small_patch2_32_mlp_im_1k_32.pth

# msn part
rand_size: 36
focal_size: 16
rand_views: 1
focal_views: 10
num_proto: 1024
hidden_dim: 2048
output_dim: 256
freeze_proto: False
patch_drop: 0.2
temperature: 0.1
me_max: True
memax_weight: 1.0
ent_weight: 0.0